name: Cut Release
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use'
        required: true
        default: 'master'
jobs:
  call-common-workflow:
    uses: dominant-strategies/quai-cicd/.github/workflows/cut-release-common.yml@main
    with:
      branch: ${{ github.event.inputs.branch }}
      needs_build: true
      needs_docker: false
      install_command: "npm ci"
      build_command: "npm run build-clean"
      cloud_deploy: false
      skip_deploy: true
      update_version: true
      include_chart: false
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      BUILD_ARGS: ''
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY2 }}
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
  update-docs:
    runs-on: ubuntu-latest
    needs: call-common-workflow
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
          ssh-key: ${{ secrets.GH_PAT }}

      - name: Install dependencies
        run: npm ci

      - name: Generate documentation with TypeDoc
        run: npx typedoc

      - uses: actions/checkout@v3
        with:
          repository: dominant-strategies/quais-docs
          ssh-key: ${{ secrets.GH_PAT }}
          path: quais-docs

      - name: Import GPG Key
        if: ${{ inputs.update_version }}
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY2 }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --import
          git config --global user.signingkey $GPG_KEY_ID
          git config --global commit.gpgsign true
          # Configure Git with CI account details
          git config --global user.name "ci-dominantstrategies"
          git config --global user.email "ci@dominantstrategies.io"
          
          # Optionally, check that the GPG key is correctly configured for signing
          gpg --list-keys "ci@dominantstrategies.io"

      - name: generate docs content
        run: npx typedoc

      - name: Copy generated documentation
        run: |
          mkdir -p docs-repo/docs/content
          cp -r docs/content/* quais-docs/content/
          cd quais-docs/scripts
          node updateNavigation.js

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: quais-docs
          branch: main
          commit_user_name: ci-dominantstrategies
          commit_user_email: ci@dominantstrategies.io
        env:
          HUSKY: 0
